### ISSUE TITLE
licence

### ISSUE THREAD

**Issue by treinen** [ocaml-ppx/ppx_derivers#1]
Bonjour Jérémy,

I was just packaging for debian your ppx_derivers. However, even though you say in the opam file that its is has a BSD3 licence, there is no COPYRIGHT file in the archive and no copyright header in
the source files. Could you please add these ?

Merci  -Ralf.

**Comment by tautschnig** [comment]
Ping?

**Comment by ghost** [comment]
Bonjour Ralf,

Sorry, I missed this ticket. I just added a LICENSE.md file, let me know if it's all good and I can do a new  release.

**Comment by tautschnig** [comment]
Thank you!

**Comment by treinen** [comment]
Bonjour Jérémie, c'est parfait, merci ! -Ralf.

**Comment by ghost** [comment]
No problem. I created a 1.1 release with the LICENSE.md file included

**Comment by treinen** [comment]
Thanks ! Just a small remark : the copyright year is probably not 2011 ... -Ralf

**Comment by ghost** [comment]
Oops... Fixed in master. Let me know if you need another release

**Comment by treinen** [comment]
Hello, it would indeed help if you could do a new release. Sorry about this but any newly created debian package will be scrutinized by the debian ftp masters, and they look in particular at license issues, so having the copyright year fixed upstream will remove one possible source of problems. -Ralf.

**Comment by ghost** [comment]
No problem. I created a 1.2 release.
