### ISSUE TITLE
does not compile on byte-code-only architectures

### ISSUE THREAD

**Issue by treinen** [ocaml-ppx/ppx_derivers#2]
Hello, ppx_derivers does not compile on architectures which only have a bytecode compiler, like mips. It fails with the message

jbuilder build @install
No rule found for _build/default/src/ppx_derivers.cmx
make[1]: *** [Makefile:5: all] Error 1

a complete build log is here:

https://buildd.debian.org/status/fetch.php?pkg=ppx-derivers&arch=mips&ver=1.2-1&stamp=1520289651&raw=0

**Comment by ghost** [comment]
This was fixed in jbuilder beta18: https://github.com/ocaml/dune/issues/330

**Comment by treinen** [comment]
Yes, it compiles now on bytecode-only archs using recent dune. -Ralf.
